#!/bin/sh

tvh_deb="$(find /out -name 'tvheadend_*.deb')"
tvh_changes="$(find /out -name 'tvheadend_*.changes')"
tvh_dbg_deb="$(find /out -name 'tvheadend-dbg_*.deb')"
tvh_ver="$(echo $tvh_deb | sed -e 's|.*/tvheadend_||' -e 's|~trusty.*||')"

bintray_ver_desc="Tvheadend on ubuntu.
Master branch.

https://github.com/tvheadend/tvheadend

Tvheadend is a TV streaming server and recorder for Linux, FreeBSD and Android supporting DVB-S, DVB-S2, DVB-C, DVB-T, ATSC, IPTV, SAT>IP and HDHomeRun as input sources.

https://tvheadend.org/"

# Create a new version
curl -sS -u${bintray_user}:${bintray_key} -H "Content-Type: application/json" \
	-X POST https://api.bintray.com/packages/${bintray_user}/${bintray_repo}/${bintray_pkg_name}/versions \
	--data "{ \"name\": \"${tvh_ver}\", \"desc\": \"${bintray_ver_desc}\", }"

# Upload files
for distfile in $tvh_deb $tvh_changes $tvh_dbg_deb; do
		deb_repo_path="pool/main/t/tvheadend/$(basename ${distfile})"
    curl -sS -T $distfile -u${bintray_user}:${bintray_key} -H X-Bintray-Version:$tvh_ver https://api.bintray.com/content/${bintray_user}/${bintray_repo}/${bintray_pkg_name}/${tvh_ver}/${deb_repo_path}\;deb_distribution=${deb_dist}\;deb_component=${deb_component}\;deb_architecture=amd64\;publish=1
done



