#!/usr/bin/with-contenv sh


# Set the uid:gid to run as
[ "$hp_uid" ] && usermod  -o -u "$hp_uid" headphones
[ "$hp_gid" ] && groupmod -o -g "$hp_gid" headphones


# chown if don't have permission to write to config and logs folders
[ "$(stat -c %U:%G /config )" = "headphones:headphones" ] || chown -R headphones:headphones /config


if [ "$pipework_wait" ]; then
	for _pipework_if in $pipework_wait; do
		echo "znc: Waiting for pipework to bring up $_pipework_if..."
		pipework --wait -i $_pipework_if
	done
	sleep 1
fi


# Copy "$@" special variable into a regular variable
_headphones_args="$@"


# Start headphones. web UI should bind to * automatically
sudo -E su "headphones" << EOF
	set -x

	# Check the config file exists in /config, else copy it in
	[ -e "/config/config.ini" ] || cp -Rf /etc/config.preseed/* /config/

	cd /headphones
	python ./Headphones.py --nolaunch --datadir /config --config /config/config.ini $_headphones_args
EOF



# # ./Headphones.py --help
# usage: Headphones.py [-h] [-v] [-q] [-d] [-p PORT] [--datadir DATADIR]
#                      [--config CONFIG] [--nolaunch] [--pidfile PIDFILE]

# Music add-on for SABnzbd+, Transmission and more.

# optional arguments:
#   -h, --help            show this help message and exit
#   -v, --verbose         Increase console logging verbosity
#   -q, --quiet           Turn off console logging
#   -d, --daemon          Run as a daemon
#   -p PORT, --port PORT  Force Headphones to run on a specified port
#   --datadir DATADIR     Specify a directory where to store your data files
#   --config CONFIG       Specify a config file to use
#   --nolaunch            Prevent browser from launching on startup
#   --pidfile PIDFILE     Create a pid file (only relevant when running as a
#                         daemon)






























