#!/usr/bin/with-contenv sh


# Set the uid:gid to run as
[ "$atheme_uid" ] && usermod  -o -u "$atheme_uid" atheme
[ "$atheme_gid" ] && groupmod -o -g "$atheme_gid" atheme


# Check the config file exists in /config, else copy it in
[ -e "/config/atheme/atheme.conf" ] || cp -Rf "/etc/config.preseed/atheme" "/config"
mkdir -p /irc/atheme


# chown if don't have permission to write to the config folder
[ "$(stat -c %U:%G /config/atheme )" = "atheme:atheme" ] || chown -R atheme:atheme /config/atheme
[ "$(stat -c %U:%G /irc/atheme )" = "atheme:atheme" ] || chown -R atheme:atheme /irc/atheme


# All roads lead to /irc/atheme
for _dir in lib log run; do
	rm -rf /var/$_dir/atheme
	ln -sf /irc/atheme /var/$_dir/atheme
done


sudo -E su "atheme" << EOF
	set -x

	# Launch atheme-services
	/usr/bin/atheme-services -n -c /config/atheme/atheme.conf -l /irc/atheme/atheme.log -p /config/atheme/atheme.pid

EOF




# # xtheme-services --help
# unknown option -- help
# usage: xtheme [-dhnvr] [-c conf] [-l logfile] [-p pidfile]

# $ atheme-services --help
# unknown option -- help
# usage: atheme [-dhnvr] [-c conf] [-l logfile] [-p pidfile]

# OPTIONS
#        atheme-services accepts the following command line options:
#        -c conf
#               Specifies an alternate config file for the daemon to load.
#        -d     Starts in debugging mode.
#        -h     Prints the help message and exits.
#        -l logfile
#               Specifies the log file.
#        -n     Doesn't  fork  into  the  background, logs messages to stdout as
#               well as the logfile.
#        -p pidfile
#               Specifies the pid file.
#        -v     Prints the version information and exits.

# +
# "startup flag -r (read-only) added."



