#!/usr/bin/with-contenv sh


# Set the uid:gid to run as
[ "$cp_uid" ] && usermod  -o -u "$cp_uid" couchpotato
[ "$cp_gid" ] && groupmod -o -g "$cp_gid" couchpotato


# chown if don't have permission to write to /config
[ "$(stat -c %U:%G /config )" = "couchpotato:couchpotato" ] || chown -R couchpotato:couchpotato /config
[ "$(stat -c %U:%G /couchpotato )" = "couchpotato:couchpotato" ] || chown -R couchpotato:couchpotato /couchpotato


if [ "$pipework_wait" ]; then
	for _pipework_if in $pipework_wait; do
		echo "znc: Waiting for pipework to bring up $_pipework_if..."
		pipework --wait -i $_pipework_if
	done
	sleep 1
fi


# Ensure $HOSTNAME can be pinged otherwise couchpotato will fail to start
ping -q -c1 $(hostname) > /dev/null 2>&1 || echo "$_lan_ip $(hostname)" >> /etc/hosts


# Copy "$@" special variable into a regular variable
_couchpotato_args="$@"


# Start couchpotato. web UI should bind to * automatically
sudo -E su "couchpotato" << EOF
	set -x


	# Check the config file exists in /config, else copy it in
	[ -e "/config/settings.conf" ] || cp -Rf /etc/config.preseed/* /config/


	cd /couchpotato
	python ./CouchPotato.py --console_log --data_dir /config --debug $_couchpotato_args
EOF









# # ./CouchPotato.py --help
# usage: CouchPotato.py [-h] [--data_dir DATA_DIR] [--config_file CONFIG_FILE]
#                       [--debug] [--console_log] [--quiet] [--daemon]
#                       [--pid_file PID_FILE]

# optional arguments:
#   -h, --help            show this help message and exit
#   --data_dir DATA_DIR   Absolute or ~/ path of the data dir
#   --config_file CONFIG_FILE
#                         Absolute or ~/ path of the settings file (default
#                         DATA_DIR/settings.conf)
#   --debug               Debug mode
#   --console_log         Log to console
#   --quiet               No console logging
#   --daemon              Daemonize the app
#   --pid_file PID_FILE   Path to pidfile needed for daemon
















