#!/usr/bin/with-contenv sh


# Set the uid:gid to run as
[ "$irssi_uid" ] && usermod  -o -u "$irssi_uid" irssi
[ "$irssi_gid" ] && groupmod -o -g "$irssi_gid" irssi


# Check the config file exists in /config, else copy it in
[ -e "/config/irssi/config" ] || cp -Rf "/etc/config.preseed/irssi" "/config"
mkdir -p /irc/irssi/urlplot/urls

# chown if don't have permission to write to the config and urlplot folders
[ "$(stat -c %U:%G /config/irssi )" = "irssi:irssi" ] || chown -R irssi:irssi /config/irssi
[ "$(stat -c %U:%G /irc/irssi )" = "irssi:irssi" ] || chown -R irssi:irssi /irc/irssi


if [ "$pipework_wait" ]; then
	for _pipework_if in $pipework_wait; do
		echo "irssi: Waiting for pipework to bring up $_pipework_if..."
		pipework --wait -i $_pipework_if
	done
	sleep 1
fi


# Update irssi scripts
cd /scripts.irssi.org && git pull && cd /


# Alias 'irssi' to connect to running tmux session
touch ~/.profile ~/.bashrc
grep -q "alias irssi" ~/.profile || echo "alias irssi=\"sudo -E -u irssi script -q -e /dev/null -c 'tmux -S $tmux_socket -u attach-session -t $tmux_session'\"" >> ~/.profile
grep -q "alias irssi" ~/.bashrc || echo "alias irssi=\"sudo -E -u irssi script -q -e /dev/null -c 'tmux -S $tmux_socket -u attach-session -t $tmux_session'\"" >> ~/.bashrc


sudo -E su "irssi" << EOF
	set -x

	# Generate ssh key pair
	if [ ! -e "/config/irssi/.ssh/authorized_keys" ]; then
		ssh-keygen -q -t rsa -N "" -f id_rsa
		cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
	fi


	# Alias 'irssi' to connect to running tmux session
	touch ~/.profile ~/.bashrc
	grep -q "alias irssi" ~/.profile || echo "alias irssi=\"script -q -e /dev/null -c 'tmux -S $tmux_socket -u attach-session -t $tmux_session'\"" >> ~/.profile
	grep -q "alias irssi" ~/.bashrc || echo "alias irssi=\"script -q -e /dev/null -c 'tmux -S $tmux_socket -u attach-session -t $tmux_session'\"" >> ~/.bashrc


	# Launch irssi in tmux where $tmux_socket and $tmux_session are declared in the Dockerfile ENV
	# sleep 3
	sleep 1
	script -q -e /dev/null -c "tmux -S $tmux_socket -u new-session -d -s $tmux_session -x 120 -y 40 /usr/bin/irssi --home=/config/irssi $irssi_args"
EOF


# Block while tmux session is still running
while true; do
	script -q -e /dev/null -c "tmux -S $tmux_socket -u list-sessions -F '#{session_name}'" | grep -q "^$tmux_session" || break
	sleep 3
done




# [ ** ] To connect to this ZNC you need to connect to it as your IRC server
# [ ** ] using the port that you supplied.  You have to supply your login info
# [ ** ] as the IRC server password like this: user/network:pass.
# [ ** ]
# [ ** ] Try something like this in your IRC client...
# [ ** ] /server <znc_server_ip> +6697 dreamcat4:<pass>
# [ ** ]
# [ ** ] To manage settings, users and networks, point your web browser to
# [ ** ] https://<znc_server_ip>:6697/




# root@irssi:/# irssi --help
# Usage:
#   irssi [OPTION...]

# Help Options:
#   -?, --help                  Show help options

# Application Options:
#   --config=PATH               Configuration file location (~/.irssi/config)
#   --home=PATH                 Irssi home dir location (~/.irssi)
#   -c, --connect=SERVER        Automatically connect to server/network
#   -w, --password=PASSWORD     Autoconnect password
#   -p, --port=PORT             Autoconnect port
#   -!, --noconnect             Disable autoconnecting
#   -n, --nick                  Specify nick to use
#   -h, --hostname              Specify host name to use
#   -d, --dummy                 Use the dummy terminal mode
#   -v, --version               Display irssi version


