#!/usr/bin/with-contenv sh

[ "$debug" ] && set -x


# Include common helper functions
. /etc/services.d/_includes/helpers.sh



_deluged_pid_file="/config/deluge/deluged.pid"

_cleanup ()
{
    [ "$_socat_pid" ] && kill $_socat_pid
    [ -e "$_deluged_pid_file" ] && rm -f $_deluged_pid_file
}
trap _cleanup TERM INT QUIT HUP


# Set the uid:gid to run as
[ "$deluge_uid" ] && usermod  -o -u "$deluge_uid" deluge
[ "$deluge_gid" ] && groupmod -o -g "$deluge_gid" deluge


# Check the config file exists in /config, else copy it in
[ -e "/config/deluge/core.conf" ] || cp -Rf "/etc/config.preseed/deluge" "/config"


# chown if don't have permission to write to the config folder
[ "$(stat -c %U:%G /config/deluge )" = "deluge:deluge" ] || chown -R deluge:deluge /config/deluge


# chown -r /downloads & /torrents only if owned by root. We asume that means it's a docker volume
[ "$(stat -c %u:%g /torrents )" = "0:0" ] && chown deluge:deluge /torrents
[ "$(stat -c %u:%g /downloads)" = "0:0" ] && chown deluge:deluge /downloads


# Wait for openvpn to connect successfully
# Returns:
#   $_openvpn_local_ip
#   $_openvpn_interface
_wait_for_openvpn;


# Bind to vpn interface instead of lan
while true; do
  if [ "$_openvpn_local_ip" ]; then
    _wan_if_flags="$_wan_if_flags --interface=$_openvpn_local_ip"
    break
  fi

  sleep 1
done


# Make sure the .pid file doesn't exist
rm -f "$_deluged_pid_file"


# Make sure we know the deluge daemon port number
[ "$deluge_daemon_port" ] || deluge_daemon_port="58846"


_get_lan_ip;

if [ "$_lan_ip" ]; then
  # forward deluge daemon localhost ---> lan interface
  socat tcp4-listen:${deluge_daemon_port},bind=$_lan_ip,fork tcp:localhost:${deluge_daemon_port} &
  _socat_pid=$!

else
  echo "error: _lan_ip could not be determined"
  echo "warning: deluge daemon will not be accessible except on the container's localhost interface"
fi


# Ensure $HOSTNAME can be pinged otherwise WAN networking will not work
ping -q -c1 $(hostname) > /dev/null 2>&1 || echo "$_lan_ip $(hostname)" >> /etc/hosts

if [ "$deluge_dry_run" ]; then
  while true; do
    echo 
    echo Ready to start deluge daemon!
    echo

    echo deluged --do-not-daemonize --config=/config/deluge $_wan_if_flags $_deluged_args
    echo
    sleep 10
  done
fi

# Start the deluge daemon. web UI should start automatically based on the default config
sudo -E su "deluge" << EOF
  set -x
  deluged --do-not-daemonize --config=/config/deluge $_wan_if_flags $_deluged_args
EOF


_cleanup;

