#!/bin/sh
# cron-env - a small script to print cron environment variables

# add this line to your crontab with 'crontab -e' (or 'cru' on some systems).
# * * * * * /tmp/cron-env > /tmp/cron-env.log
#
# it will run every minute. So get the file and then remove the cron line.

echo "$ env"
env
echo
echo SHELL=$SHELL
echo PATH=$PATH
echo
echo HOME=$HOME
echo USER=$USER
echo LOGNAME=$LOGNAME
echo MAILTO=$MAILTO




