#!/bin/sh

# Source settings
. /out/bintray-env

# This is specified when adding apt sources
deb_component="main"

# Boilerplate description
bintray_ver_desc="Tvheadend on ubuntu - https://tvheadend.org/
$oneline_desc


# 1. Add Bintray's GPG key:
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61


# 2. Add this repo to your sources.list:

# tvheadend - $oneline_desc
echo deb https://dl.bintray.com/dreamcat4/ubuntu $deb_dist main | sudo tee -a /etc/apt/sources.list
"

set -x
tvh_deb="$(find /out -name 'tvheadend_*.deb')"
tvh_changes="$(find /out -name 'tvheadend_*.changes')"
tvh_dbg_deb="$(find /out -name 'tvheadend-dbg_*.deb')"
tvh_ver="$(echo $tvh_deb | sed -e 's|.*/tvheadend_||' -e 's|~precise.*||' -e 's|~trusty.*||')"
set +x

# Create a new version
echo curl -sS -i -u${bintray_user}:\${bintray_key} -H "Content-Type: application/json" \
	-X POST https://api.bintray.com/packages/${bintray_user}/${bintray_repo}/${bintray_pkg_name}/versions \
	--data "{ \"name\": \"${tvh_ver}\", \"desc\": \"${bintray_ver_desc}\", }"

bintray_api_resp="$(curl -sS -i -u${bintray_user}:${bintray_key} -H "Content-Type: application/json" \
	-X POST https://api.bintray.com/packages/${bintray_user}/${bintray_repo}/${bintray_pkg_name}/versions \
	--data "{ \"name\": \"${tvh_ver}\", \"desc\": \"${bintray_ver_desc}\", }" | tr -d '\"')"

bintray_api_http_status="$(echo "$bintray_api_resp" | head -1 | cut -d' ' -f2)"

if echo "$bintray_api_resp" | grep -qi "already exists"; then
	echo "Aborting. Version ${tvh_ver} of ${bintray_pkg_name} has already been upladed to bintray."
	echo "API response: ^$bintray_api_resp$"
	exit 0
fi

if [ $bintray_api_http_status -ge 400 ]; then
	echo "Upload error. Could not create a new pkg version on bintray."
	echo "API response: ^$bintray_api_resp$"
	exit 1
else
	echo "$bintray_api_resp"
fi


# Upload files
for distfile in $tvh_deb $tvh_changes $tvh_dbg_deb; do
		deb_repo_path="pool/main/t/tvheadend/$(basename ${distfile})"

		echo curl -sS -i -T $distfile -u${bintray_user}:\${bintray_key} -H X-Bintray-Version:$tvh_ver \
      https://api.bintray.com/content/${bintray_user}/${bintray_repo}/${bintray_pkg_name}/${tvh_ver}/${deb_repo_path}\;deb_distribution=${deb_dist}\;deb_component=${deb_component}\;deb_architecture=amd64\;publish=1

    bintray_api_resp="$(curl -sS -i -T $distfile -u${bintray_user}:${bintray_key} -H X-Bintray-Version:$tvh_ver \
      https://api.bintray.com/content/${bintray_user}/${bintray_repo}/${bintray_pkg_name}/${tvh_ver}/${deb_repo_path}\;deb_distribution=${deb_dist}\;deb_component=${deb_component}\;deb_architecture=amd64\;publish=1 | tr -d '\"')"

		bintray_api_http_status="$(echo "$bintray_api_resp" | head -1 | cut -d' ' -f2)"

		if [ $bintray_api_http_status -ge 400 ]; then
			echo "Upload error. Could not upload to bintray."
			echo "API response: ^$bintray_api_resp$"
			exit 1
		else
			echo "$bintray_api_resp"
		fi
done



