#!/usr/bin/with-contenv sh


# DEPRECATED: iscsi-target / istgt
# THIS NEEDS TO BE RE-WRITTEN FOR OPEN-ISCSI INSTEAD

rm -f /iscsi/ietd.conf



i=0
for _dd_image in /iscsi/targets/*; do

	if [ -e "$_dd_image" ]; then

		echo "Target iqn.0000-00.dkr.iscsi:$(basename $_dd_image)
        Lun 0 Path=${_dd_image},Type=fileio,ScsiId=lun0,ScsiSN=lin0

" >> /iscsi/ietd.conf

	fi
done




# listen on port 0.0.0.0:3260
ietd --foreground --uid=0  --gid=0 --config=/iscsi/ietd.conf


# # list of all kmods
# for kmod in ibft sysfs target_mod tcp trgt; do modprobe iscsi_${kmod}; done




