#!/bin/sh


# Your Bintray account user settings need to go here:
bintray_user="dreamcat4"
bintray_key="0123456789abcdef0123456789abcdef01234567"


# The program name and the repo we are uploading it to - should be kept the same
bintray_repo="ubuntu"
bintray_pkg_name="tvheadend"


# The 'Debian distro' field is the first of 2 keywords when adding to apt sources
deb_dist="unstable"
oneline_desc="Unstable Releases"


