#!/usr/bin/with-contenv sh

[ "$debug" ] && set -x


# Include common helper functions
. /etc/services.d/_includes/helpers.sh


rm -f /config/openvpn/pia_listen_port

_openvpn_pid_file="/config/openvpn/openvpn.pid"


# Check the config file exists in /config, else copy it in
[ -e "/config/openvpn/default.conf" ] || cp -Rf "/etc/config.preseed/openvpn" "/config"



# Set PIA gateway
[ "$pia_gateway" ] || pia_gateway="swiss.privateinternetaccess.com"

# Set PIA openvpn service port
[ "$pia_openvpn_port" ] || pia_openvpn_port="1198"

# Update config file
sed "s/^remote\s.*$/remote ${pia_gateway} ${pia_openvpn_port}/" -i /config/openvpn/default.conf 



# Start openvpn
exec /usr/sbin/openvpn --cd /config/openvpn --config /config/openvpn/default.conf --redirect-gateway $_openvpn_flags

# When connection drops out,
# trigger a break from "sleep $_pia_port_lifetime" in the other s6 service

# New bind ip address and listen port will be assigned to deluge after reconnection
s6-svc -wu -k /var/run/s6/services/pia_update_listen_port









